#ifndef LLVM_CLANG_TOOLS_EXTRA_TEST_CLANG_TIDY_INPUTS_MODERNIZE_REDUNDANT_VOID_ARG_MODERNIZE_REDUNDANT_VOID_ARG_H
#define LLVM_CLANG_TOOLS_EXTRA_TEST_CLANG_TIDY_INPUTS_MODERNIZE_REDUNDANT_VOID_ARG_MODERNIZE_REDUNDANT_VOID_ARG_H

extern int foo(void);
// CHECK-MESSAGES: :[[@LINE-1]]:16: warning: redundant void argument list in function declaration [modernize-redundant-void-arg]
// CHECK-FIXES: {{^}}extern int foo();{{$}}

#endif // LLVM_CLANG_TOOLS_EXTRA_TEST_CLANG_TIDY_INPUTS_MODERNIZE_REDUNDANT_VOID_ARG_MODERNIZE_REDUNDANT_VOID_ARG_H
